{
    "$schema": "vscode://schemas/color-theme",
    "type": "dark",
    "colors": {
        "activityBar.activeBorder": "#e0def4",
        "activityBar.background": "#222222",
        "activityBar.dropBorder": "#26233a",
        "activityBar.foreground": "#e0def4",
        "activityBar.inactiveForeground": "#908caa",
        "activityBarBadge.background": "#ebbcba",
        "activityBarBadge.foreground": "#191724",
        "badge.background": "#ebbcba",
        "badge.foreground": "#191724",
        "banner.background": "#222222",
        "banner.foreground": "#e0def4",
        "banner.iconForeground": "#908caa",
        "breadcrumb.activeSelectionForeground": "#222222",
        "breadcrumb.background": "#222222",
        "breadcrumb.focusForeground": "#908caa",
        "breadcrumb.foreground": "#a7a7a7",
        "breadcrumbPicker.background": "#333333",
        "button.background": "#ebbcba",
        "button.foreground": "#191724",
        "button.hoverBackground": "#ebbcbae6",
        "button.secondaryBackground": "#222222",
        "button.secondaryForeground": "#e0def4",
        "button.secondaryHoverBackground": "#26233a",
        "charts.blue": "#9ccfd8",
        "charts.foreground": "#e0def4",
        "charts.green": "#31748f",
        "charts.lines": "#908caa",
        "charts.orange": "#ebbcba",
        "charts.purple": "#c4a7e7",
        "charts.red": "#eb6f92",
        "charts.yellow": "#f6c177",
        "checkbox.background": "#222222",
        "checkbox.border": "#6e6a8633",
        "checkbox.foreground": "#e0def4",
        "debugExceptionWidget.background": "#222222",
        "debugExceptionWidget.border": "#6e6a8633",
        "debugIcon.breakpointCurrentStackframeForeground": "#908caa",
        "debugIcon.breakpointDisabledForeground": "#908caa",
        "debugIcon.breakpointForeground": "#908caa",
        "debugIcon.breakpointStackframeForeground": "#908caa",
        "debugIcon.breakpointUnverifiedForeground": "#908caa",
        "debugIcon.continueForeground": "#908caa",
        "debugIcon.disconnectForeground": "#908caa",
        "debugIcon.pauseForeground": "#908caa",
        "debugIcon.restartForeground": "#908caa",
        "debugIcon.startForeground": "#908caa",
        "debugIcon.stepBackForeground": "#908caa",
        "debugIcon.stepIntoForeground": "#908caa",
        "debugIcon.stepOutForeground": "#908caa",
        "debugIcon.stepOverForeground": "#908caa",
        "debugIcon.stopForeground": "#eb6f92",
        "debugToolBar.background": "#222222",
        "debugToolBar.border": "#26233a",
        "descriptionForeground": "#908caa",
        "diffEditor.border": "#26233a",
        "diffEditor.diagonalFill": "#6e6a8666",
        "diffEditor.insertedLineBackground": "#9ccfd826",
        "diffEditor.insertedTextBackground": "#9ccfd826",
        "diffEditor.removedLineBackground": "#eb6f9226",
        "diffEditor.removedTextBackground": "#eb6f9226",
        "diffEditorOverview.insertedForeground": "#9ccfd880",
        "diffEditorOverview.removedForeground": "#eb6f9280",
        "dropdown.background": "#222222",
        "dropdown.border": "#6e6a8633",
        "dropdown.foreground": "#e0def4",
        "dropdown.listBackground": "#222222",
        "editor.background": "#222222",
        "editor.findMatchBackground": "#f6c17733",
        "editor.findMatchBorder": "#f6c17780",
        "editor.findMatchForeground": "#e0def4",
        "editor.findMatchHighlightBackground": "#6e6a8666",
        "editor.findMatchHighlightForeground": "#e0def4",
        "editor.findRangeHighlightBackground": "#6e6a8666",
        "editor.findRangeHighlightBorder": "#00000000",
        "editor.focusedStackFrameHighlightBackground": "#6e6a8633",
        "editor.foldBackground": "#222222",
        "editor.foreground": "#e0def4",
        "editor.hoverHighlightBackground": "#00000000",
        "editor.inactiveSelectionBackground": "#6e6a861a",
        "editor.inlineValuesBackground": "#00000000",
        "editor.inlineValuesForeground": "#908caa",
        "editor.lineHighlightBackground": "#6e6a861a",
        "editor.lineHighlightBorder": "#00000000",
        "editor.linkedEditingBackground": "#222222",
        "editor.rangeHighlightBackground": "#6e6a861a",
        "editor.selectionBackground": "#6e6a8633",
        "editor.selectionForeground": "#e0def4",
        "editor.selectionHighlightBackground": "#6e6a8633",
        "editor.selectionHighlightBorder": "#191724",
        "editor.snippetFinalTabstopHighlightBackground": "#6e6a8633",
        "editor.snippetFinalTabstopHighlightBorder": "#222222",
        "editor.snippetTabstopHighlightBackground": "#6e6a8633",
        "editor.snippetTabstopHighlightBorder": "#222222",
        "editor.stackFrameHighlightBackground": "#6e6a8633",
        "editor.symbolHighlightBackground": "#6e6a8633",
        "editor.symbolHighlightBorder": "#00000000",
        "editor.wordHighlightBackground": "#6e6a8633",
        "editor.wordHighlightBorder": "#00000000",
        "editor.wordHighlightStrongBackground": "#6e6a8633",
        "editor.wordHighlightStrongBorder": "#6e6a8633",
        "editorBracketHighlight.foreground1": "#eb6f9280",
        "editorBracketHighlight.foreground2": "#31748f80",
        "editorBracketHighlight.foreground3": "#f6c17780",
        "editorBracketHighlight.foreground4": "#9ccfd880",
        "editorBracketHighlight.foreground5": "#ebbcba80",
        "editorBracketHighlight.foreground6": "#c4a7e780",
        "editorBracketMatch.background": "#00000000",
        "editorBracketMatch.border": "#908caa",
        "editorBracketPairGuide.activeBackground1": "#31748f",
        "editorBracketPairGuide.activeBackground2": "#ebbcba",
        "editorBracketPairGuide.activeBackground3": "#c4a7e7",
        "editorBracketPairGuide.activeBackground4": "#9ccfd8",
        "editorBracketPairGuide.activeBackground5": "#f6c177",
        "editorBracketPairGuide.activeBackground6": "#eb6f92",
        "editorBracketPairGuide.background1": "#31748f80",
        "editorBracketPairGuide.background2": "#ebbcba80",
        "editorBracketPairGuide.background3": "#c4a7e780",
        "editorBracketPairGuide.background4": "#9ccfd880",
        "editorBracketPairGuide.background5": "#f6c17780",
        "editorBracketPairGuide.background6": "#eb6f9280",
        "editorCodeLens.foreground": "#ebbcba",
        "editorCursor.background": "#000000",
        "editorCursor.foreground": "#ffffff",
        "editorError.border": "#00000000",
        "editorError.foreground": "#00000000",
        "editorGhostText.foreground": "#908caa",
        "editorGroup.border": "#00000000",
        "editorGroup.dropBackground": "#222222",
        "editorGroup.emptyBackground": "#00000000",
        "editorGroup.focusedEmptyBorder": "#00000000",
        "editorGroupHeader.noTabsBackground": "#00000000",
        "editorGroupHeader.tabsBackground": "#00000000",
        "editorGroupHeader.tabsBorder": "#00000000",
        "editorGutter.addedBackground": "#9ccfd8",
        "editorGutter.background": "#222222",
        "editorGutter.commentRangeForeground": "#26233a",
        "editorGutter.deletedBackground": "#eb6f92",
        "editorGutter.foldingControlForeground": "#c4a7e7",
        "editorGutter.modifiedBackground": "#ebbcba",
        "editorHint.border": "#00000000",
        "editorHint.foreground": "#908caa",
        "editorHoverWidget.background": "#222222",
        "editorHoverWidget.border": "#6e6a8680",
        "editorHoverWidget.foreground": "#908caa",
        "editorHoverWidget.highlightForeground": "#e0def4",
        "editorHoverWidget.statusBarBackground": "#00000000",
        "editorIndentGuide.activeBackground": "#6e6a86",
        "editorIndentGuide.background": "#6e6a8666",
        "editorInfo.border": "#26233a",
        "editorInfo.foreground": "#00000000",
        "editorInlayHint.background": "#00000000",
        "editorInlayHint.foreground": "#868686f0",
        "editorInlayHint.parameterBackground": "#00000000",
        "editorInlayHint.parameterForeground": "#aaa5aaf0",
        "editorInlayHint.typeBackground": "#00000000",
        "editorInlayHint.typeForeground": "#aaa5aaf0",
        "editorLightBulb.foreground": "#31748f",
        "editorLightBulbAutoFix.foreground": "#ebbcba",
        "editorLineNumber.activeForeground": "#222222",
        "editorLineNumber.foreground": "#a7a7a7",
        "editorLink.activeForeground": "#ebbcba",
        "editorMarkerNavigation.background": "#222222",
        "editorMarkerNavigationError.background": "#222222",
        "editorMarkerNavigationInfo.background": "#222222",
        "editorMarkerNavigationWarning.background": "#222222",
        "editorOverviewRuler.addedForeground": "#9ccfd880",
        "editorOverviewRuler.background": "#191724",
        "editorOverviewRuler.border": "#6e6a8666",
        "editorOverviewRuler.bracketMatchForeground": "#908caa",
        "editorOverviewRuler.commentForeground": "#908caa80",
        "editorOverviewRuler.commentUnresolvedForeground": "#f6c17780",
        "editorOverviewRuler.commonContentForeground": "#6e6a861a",
        "editorOverviewRuler.currentContentForeground": "#6e6a8633",
        "editorOverviewRuler.deletedForeground": "#eb6f9280",
        "editorOverviewRuler.errorForeground": "#eb6f9280",
        "editorOverviewRuler.findMatchForeground": "#6e6a8666",
        "editorOverviewRuler.incomingContentForeground": "#c4a7e780",
        "editorOverviewRuler.infoForeground": "#9ccfd880",
        "editorOverviewRuler.modifiedForeground": "#ebbcba80",
        "editorOverviewRuler.rangeHighlightForeground": "#6e6a8666",
        "editorOverviewRuler.selectionHighlightForeground": "#6e6a8666",
        "editorOverviewRuler.warningForeground": "#f6c17780",
        "editorOverviewRuler.wordHighlightForeground": "#6e6a8633",
        "editorOverviewRuler.wordHighlightStrongForeground": "#6e6a8666",
        "editorPane.background": "#00000000",
        "editorRuler.foreground": "#6e6a8666",
        "editorSuggestWidget.background": "#222222",
        "editorSuggestWidget.border": "#00000000",
        "editorSuggestWidget.focusHighlightForeground": "#ebbcba",
        "editorSuggestWidget.foreground": "#908caa",
        "editorSuggestWidget.highlightForeground": "#ebbcba",
        "editorSuggestWidget.selectedBackground": "#6e6a8633",
        "editorSuggestWidget.selectedForeground": "#e0def4",
        "editorSuggestWidget.selectedIconForeground": "#e0def4",
        "editorUnnecessaryCode.border": "#00000000",
        "editorUnnecessaryCode.opacity": "#e0def480",
        "editorWarning.border": "#00000000",
        "editorWarning.foreground": "#00000000",
        "editorWhitespace.foreground": "#6e6a86",
        "editorWidget.background": "#222222",
        "editorWidget.border": "#26233a",
        "editorWidget.foreground": "#908caa",
        "editorWidget.resizeBorder": "#6e6a86",
        "errorForeground": "#eb6f92",
        "extensionBadge.remoteBackground": "#c4a7e7",
        "extensionBadge.remoteForeground": "#191724",
        "extensionButton.prominentBackground": "#ebbcba",
        "extensionButton.prominentForeground": "#191724",
        "extensionButton.prominentHoverBackground": "#ebbcbae6",
        "extensionIcon.preReleaseForeground": "#31748f",
        "extensionIcon.starForeground": "#ebbcba",
        "extensionIcon.verifiedForeground": "#c4a7e7",
        "focusBorder": "#6e6a8633",
        "foreground": "#e0def4",
        "gitDecoration.addedResourceForeground": "#9ccfd8",
        "gitDecoration.conflictingResourceForeground": "#eb6f92",
        "gitDecoration.deletedResourceForeground": "#908caa",
        "gitDecoration.ignoredResourceForeground": "#6e6a86",
        "gitDecoration.modifiedResourceForeground": "#ebbcba",
        "gitDecoration.renamedResourceForeground": "#31748f",
        "gitDecoration.stageDeletedResourceForeground": "#eb6f92",
        "gitDecoration.stageModifiedResourceForeground": "#c4a7e7",
        "gitDecoration.submoduleResourceForeground": "#f6c177",
        "gitDecoration.untrackedResourceForeground": "#f6c177",
        "icon.foreground": "#908caa",
        "input.background": "#26233a80",
        "input.border": "#6e6a8633",
        "input.foreground": "#e0def4",
        "input.placeholderForeground": "#908caa",
        "inputOption.activeBackground": "#ebbcba26",
        "inputOption.activeBorder": "#00000000",
        "inputOption.activeForeground": "#ebbcba",
        "inputValidation.errorBackground": "#222222",
        "inputValidation.errorBorder": "#6e6a8666",
        "inputValidation.errorForeground": "#eb6f92",
        "inputValidation.infoBackground": "#222222",
        "inputValidation.infoBorder": "#6e6a8666",
        "inputValidation.infoForeground": "#9ccfd8",
        "inputValidation.warningBackground": "#222222",
        "inputValidation.warningBorder": "#6e6a8666",
        "inputValidation.warningForeground": "#9ccfd880",
        "keybindingLabel.background": "#26233a",
        "keybindingLabel.border": "#6e6a8666",
        "keybindingLabel.bottomBorder": "#6e6a8666",
        "keybindingLabel.foreground": "#c4a7e7",
        "keybindingTable.headerBackground": "#26233a",
        "keybindingTable.rowsBackground": "#222222",
        "list.activeSelectionBackground": "#6e6a8633",
        "list.activeSelectionForeground": "#e0def4",
        "list.deemphasizedForeground": "#908caa",
        "list.dropBackground": "#222222",
        "list.errorForeground": "#eb6f92",
        "list.filterMatchBackground": "#222222",
        "list.filterMatchBorder": "#ebbcba",
        "list.focusBackground": "#6e6a8666",
        "list.focusForeground": "#e0def4",
        "list.focusOutline": "#6e6a8633",
        "list.highlightForeground": "#ebbcba",
        "list.hoverBackground": "#6e6a861a",
        "list.hoverForeground": "#e0def4",
        "list.inactiveFocusBackground": "#6e6a861a",
        "list.inactiveSelectionBackground": "#222222",
        "list.inactiveSelectionForeground": "#e0def4",
        "list.invalidItemForeground": "#eb6f92",
        "list.warningForeground": "#f6c177",
        "listFilterWidget.background": "#222222",
        "listFilterWidget.noMatchesOutline": "#eb6f92",
        "listFilterWidget.outline": "#26233a",
        "menu.background": "#222222",
        "menu.border": "#6e6a861a",
        "menu.foreground": "#e0def4",
        "menu.selectionBackground": "#6e6a8633",
        "menu.selectionBorder": "#26233a",
        "menu.selectionForeground": "#e0def4",
        "menu.separatorBackground": "#6e6a8666",
        "menubar.selectionBackground": "#6e6a8633",
        "menubar.selectionBorder": "#6e6a861a",
        "menubar.selectionForeground": "#e0def4",
        "merge.border": "#26233a",
        "merge.commonContentBackground": "#6e6a8633",
        "merge.commonHeaderBackground": "#6e6a8633",
        "merge.currentContentBackground": "#f6c17780",
        "merge.currentHeaderBackground": "#f6c17780",
        "merge.incomingContentBackground": "#9ccfd880",
        "merge.incomingHeaderBackground": "#9ccfd880",
        "minimap.background": "#222222",
        "minimap.errorHighlight": "#eb6f9280",
        "minimap.findMatchHighlight": "#6e6a8633",
        "minimap.selectionHighlight": "#6e6a8633",
        "minimap.warningHighlight": "#f6c17780",
        "minimapGutter.addedBackground": "#9ccfd8",
        "minimapGutter.deletedBackground": "#eb6f92",
        "minimapGutter.modifiedBackground": "#ebbcba",
        "minimapSlider.activeBackground": "#6e6a8666",
        "minimapSlider.background": "#6e6a8633",
        "minimapSlider.hoverBackground": "#6e6a8633",
        "notebook.cellBorderColor": "#9ccfd880",
        "notebook.cellEditorBackground": "#222222",
        "notebook.cellHoverBackground": "#26233a80",
        "notebook.focusedCellBackground": "#6e6a861a",
        "notebook.focusedCellBorder": "#9ccfd8",
        "notebook.outputContainerBackgroundColor": "#6e6a861a",
        "notificationCenter.border": "#6e6a8633",
        "notificationCenterHeader.background": "#222222",
        "notificationCenterHeader.foreground": "#908caa",
        "notificationLink.foreground": "#c4a7e7",
        "notificationToast.border": "#6e6a8633",
        "notifications.background": "#222222",
        "notifications.border": "#6e6a8633",
        "notifications.foreground": "#e0def4",
        "notificationsErrorIcon.foreground": "#eb6f92",
        "notificationsInfoIcon.foreground": "#9ccfd8",
        "notificationsWarningIcon.foreground": "#f6c177",
        "panel.background": "#222222",
        "panel.border": "#00000000",
        "panel.dropBorder": "#26233a",
        "panelInput.border": "#222222",
        "panelSection.dropBackground": "#6e6a8633",
        "panelSectionHeader.background": "#222222",
        "panelSectionHeader.foreground": "#e0def4",
        "panelTitle.activeBorder": "#6e6a8666",
        "panelTitle.activeForeground": "#e0def4",
        "panelTitle.inactiveForeground": "#908caa",
        "peekView.border": "#26233a",
        "peekViewEditor.background": "#2e2e2e",
        "peekViewEditor.matchHighlightBackground": "#6e6a8666",
        "peekViewResult.background": "#222222",
        "peekViewResult.fileForeground": "#908caa",
        "peekViewResult.lineForeground": "#908caa",
        "peekViewResult.matchHighlightBackground": "#6e6a8666",
        "peekViewResult.selectionBackground": "#6e6a8633",
        "peekViewResult.selectionForeground": "#e0def4",
        "peekViewTitle.background": "#333333",
        "peekViewTitleDescription.foreground": "#908caa",
        "pickerGroup.border": "#6e6a8666",
        "pickerGroup.foreground": "#c4a7e7",
        "ports.iconRunningProcessForeground": "#ebbcba",
        "problemsErrorIcon.foreground": "#eb6f92",
        "problemsInfoIcon.foreground": "#9ccfd8",
        "problemsWarningIcon.foreground": "#f6c177",
        "progressBar.background": "#ebbcba",
        "quickInput.background": "#222222",
        "quickInput.foreground": "#908caa",
        "quickInputList.focusBackground": "#6e6a8633",
        "quickInputList.focusForeground": "#e0def4",
        "quickInputList.focusIconForeground": "#e0def4",
        "scrollbar.shadow": "#2222224d",
        "scrollbarSlider.activeBackground": "#222222",
        "scrollbarSlider.background": "#222222",
        "scrollbarSlider.hoverBackground": "#222222",
        "searchEditor.findMatchBackground": "#6e6a8633",
        "selection.background": "#6e6a8666",
        "settings.focusedRowBackground": "#222222",
        "settings.focusedRowBorder": "#6e6a8633",
        "settings.headerForeground": "#e0def4",
        "settings.modifiedItemIndicator": "#ebbcba",
        "settings.rowHoverBackground": "#222222",
        "sideBar.background": "#222222",
        "sideBar.dropBackground": "#222222",
        "sideBar.foreground": "#a7a7a7",
        "sideBarSectionHeader.background": "#222222",
        "sideBarSectionHeader.border": "#6e6a8633",
        "sideBarSectionHeader.foreground": "#a7a7a7",
        "statusBar.background": "#222222",
        "statusBar.debuggingBackground": "#c4a7e7",
        "statusBar.debuggingForeground": "#191724",
        "statusBar.foreground": "#a7a7a7",
        "statusBar.noFolderBackground": "#191724",
        "statusBar.noFolderForeground": "#908caa",
        "statusBarItem.activeBackground": "#6e6a8666",
        "statusBarItem.errorBackground": "#191724",
        "statusBarItem.errorForeground": "#eb6f92",
        "statusBarItem.hoverBackground": "#6e6a8633",
        "statusBarItem.prominentBackground": "#26233a",
        "statusBarItem.prominentForeground": "#e0def4",
        "statusBarItem.prominentHoverBackground": "#6e6a8633",
        "statusBarItem.remoteBackground": "#191724",
        "statusBarItem.remoteForeground": "#f6c177",
        "symbolIcon.arrayForeground": "#908caa",
        "symbolIcon.classForeground": "#908caa",
        "symbolIcon.colorForeground": "#908caa",
        "symbolIcon.constantForeground": "#908caa",
        "symbolIcon.constructorForeground": "#908caa",
        "symbolIcon.enumeratorForeground": "#908caa",
        "symbolIcon.enumeratorMemberForeground": "#908caa",
        "symbolIcon.eventForeground": "#908caa",
        "symbolIcon.fieldForeground": "#908caa",
        "symbolIcon.fileForeground": "#908caa",
        "symbolIcon.folderForeground": "#908caa",
        "symbolIcon.functionForeground": "#908caa",
        "symbolIcon.interfaceForeground": "#908caa",
        "symbolIcon.keyForeground": "#908caa",
        "symbolIcon.keywordForeground": "#908caa",
        "symbolIcon.methodForeground": "#908caa",
        "symbolIcon.moduleForeground": "#908caa",
        "symbolIcon.namespaceForeground": "#908caa",
        "symbolIcon.nullForeground": "#908caa",
        "symbolIcon.numberForeground": "#908caa",
        "symbolIcon.objectForeground": "#908caa",
        "symbolIcon.operatorForeground": "#908caa",
        "symbolIcon.packageForeground": "#908caa",
        "symbolIcon.propertyForeground": "#908caa",
        "symbolIcon.referenceForeground": "#908caa",
        "symbolIcon.snippetForeground": "#908caa",
        "symbolIcon.stringForeground": "#908caa",
        "symbolIcon.structForeground": "#908caa",
        "symbolIcon.textForeground": "#908caa",
        "symbolIcon.typeParameterForeground": "#908caa",
        "symbolIcon.unitForeground": "#908caa",
        "symbolIcon.variableForeground": "#908caa",
        "tab.activeBackground": "#6e6a861a",
        "tab.activeForeground": "#e0def4",
        "tab.activeModifiedBorder": "#9ccfd8",
        "tab.border": "#00000000",
        "tab.hoverBackground": "#6e6a8633",
        "tab.inactiveBackground": "#00000000",
        "tab.inactiveForeground": "#908caa",
        "tab.inactiveModifiedBorder": "#9ccfd880",
        "tab.lastPinnedBorder": "#6e6a86",
        "tab.unfocusedActiveBackground": "#00000000",
        "tab.unfocusedHoverBackground": "#00000000",
        "tab.unfocusedInactiveBackground": "#00000000",
        "tab.unfocusedInactiveModifiedBorder": "#9ccfd880",
        "terminal.ansiBlack": "#26233a",
        "terminal.ansiBlue": "#9ccfd8",
        "terminal.ansiBrightBlack": "#908caa",
        "terminal.ansiBrightBlue": "#9ccfd8",
        "terminal.ansiBrightCyan": "#ebbcba",
        "terminal.ansiBrightGreen": "#31748f",
        "terminal.ansiBrightMagenta": "#c4a7e7",
        "terminal.ansiBrightRed": "#eb6f92",
        "terminal.ansiBrightWhite": "#e0def4",
        "terminal.ansiBrightYellow": "#f6c177",
        "terminal.ansiCyan": "#ebbcba",
        "terminal.ansiGreen": "#31748f",
        "terminal.ansiMagenta": "#c4a7e7",
        "terminal.ansiRed": "#eb6f92",
        "terminal.ansiWhite": "#e0def4",
        "terminal.ansiYellow": "#f6c177",
        "terminal.dropBackground": "#6e6a8633",
        "terminal.foreground": "#e0def4",
        "terminal.selectionBackground": "#6e6a8633",
        "terminal.tab.activeBorder": "#e0def4",
        "terminalCursor.background": "#ffffff",
        "terminalCursor.foreground": "#ffffff",
        "textBlockQuote.background": "#222222",
        "textBlockQuote.border": "#6e6a8633",
        "textCodeBlock.background": "#222222",
        "textLink.activeForeground": "#c4a7e7e6",
        "textLink.foreground": "#c4a7e7",
        "textPreformat.foreground": "#f6c177",
        "textSeparator.foreground": "#908caa",
        "titleBar.activeBackground": "#222222",
        "titleBar.activeForeground": "#a7a7a7",
        "titleBar.inactiveBackground": "#222222",
        "titleBar.inactiveForeground": "#a7a7a7",
        "toolbar.activeBackground": "#6e6a8666",
        "toolbar.hoverBackground": "#6e6a8633",
        "tree.indentGuidesStroke": "#908caa",
        "walkThrough.embeddedEditorBackground": "#191724",
        "welcomePage.background": "#191724",
        "widget.shadow": "#2222224d",
        "window.activeBorder": "#222222",
        "window.inactiveBorder": "#222222",
        //"actionBar.toggledBackground": "#ebbcba26",
        //"activityBarTop.activeBorder": "#e7e7e7",
        //"activityBarTop.dropBorder": "#e7e7e7",
        //"activityBarTop.foreground": "#e7e7e7",
        //"activityBarTop.inactiveForeground": "#e7e7e799",
        //"activityErrorBadge.background": "#f14c4c",
        //"activityErrorBadge.foreground": "#000000",
        //"activityWarningBadge.background": "#cca700",
        //"activityWarningBadge.foreground": "#000000",
        //"button.separator": "#19172466",
        //"chat.avatarBackground": "#1f1f1f",
        //"chat.avatarForeground": "#e0def4",
        //"chat.editedFileForeground": "#e2c08d",
        //"chat.requestBackground": "#2222229e",
        //"chat.requestBorder": "#ffffff1a",
        //"chat.slashCommandBackground": "#34414b8f",
        //"chat.slashCommandForeground": "#40a6ff",
        //"checkbox.selectBackground": "#222222",
        //"checkbox.selectBorder": "#908caa",
        //"commandCenter.activeBackground": "#ffffff14",
        //"commandCenter.activeBorder": "#a7a7a74d",
        //"commandCenter.activeForeground": "#e0def4",
        //"commandCenter.background": "#ffffff0d",
        //"commandCenter.border": "#a7a7a733",
        //"commandCenter.debuggingBackground": "#c4a7e742",
        //"commandCenter.foreground": "#a7a7a7",
        //"commandCenter.inactiveBorder": "#a7a7a740",
        //"commandCenter.inactiveForeground": "#a7a7a7",
        //"commentsView.resolvedIcon": "#cccccc80",
        //"commentsView.unresolvedIcon": "#6e6a8633",
        //"debugConsole.errorForeground": "#eb6f92",
        //"debugConsole.infoForeground": "#00000000",
        //"debugConsole.sourceForeground": "#e0def4",
        //"debugConsole.warningForeground": "#00000000",
        //"debugConsoleInputIcon.foreground": "#e0def4",
        //"debugTokenExpression.boolean": "#4e94ce",
        //"debugTokenExpression.error": "#f48771",
        //"debugTokenExpression.name": "#c586c0",
        //"debugTokenExpression.number": "#b5cea8",
        //"debugTokenExpression.string": "#ce9178",
        //"debugTokenExpression.type": "#4a90e2",
        //"debugTokenExpression.value": "#cccccc99",
        //"debugView.exceptionLabelBackground": "#6c2022",
        //"debugView.exceptionLabelForeground": "#e0def4",
        //"debugView.stateLabelBackground": "#88888844",
        //"debugView.stateLabelForeground": "#e0def4",
        //"debugView.valueChangedHighlight": "#569cd6",
        //"diffEditor.move.border": "#8b8b8b9c",
        //"diffEditor.moveActive.border": "#ffa500",
        //"diffEditor.unchangedCodeBackground": "#74747429",
        //"diffEditor.unchangedRegionBackground": "#222222",
        //"diffEditor.unchangedRegionForeground": "#e0def4",
        //"diffEditor.unchangedRegionShadow": "#000000",
        //"disabledForeground": "#cccccc80",
        //"editor.compositionBorder": "#ffffff",
        //"editor.foldPlaceholderForeground": "#808080",
        //"editor.placeholder.foreground": "#908caa",
        //"editor.wordHighlightTextBackground": "#6e6a8633",
        //"editor.wordHighlightTextBorder": "#00000000",
        //"editorActionList.background": "#222222",
        //"editorActionList.focusBackground": "#6e6a8633",
        //"editorActionList.focusForeground": "#e0def4",
        //"editorActionList.foreground": "#908caa",
        //"editorActiveLineNumber.foreground": "#c6c6c6",
        //"editorBracketHighlight.unexpectedBracket.foreground": "#ff1212cc",
        //"editorCommentsWidget.rangeActiveBackground": "#6e6a8605",
        //"editorCommentsWidget.rangeBackground": "#6e6a8605",
        //"editorCommentsWidget.replyInputBackground": "#333333",
        //"editorCommentsWidget.resolvedBorder": "#cccccc80",
        //"editorCommentsWidget.unresolvedBorder": "#6e6a8633",
        //"editorGroup.dropIntoPromptBackground": "#222222",
        //"editorGroup.dropIntoPromptForeground": "#908caa",
        //"editorGutter.commentGlyphForeground": "#e0def4",
        //"editorGutter.commentUnresolvedGlyphForeground": "#e0def4",
        //"editorIndentGuide.activeBackground1": "#6e6a86",
        //"editorIndentGuide.activeBackground2": "#00000000",
        //"editorIndentGuide.activeBackground3": "#00000000",
        //"editorIndentGuide.activeBackground4": "#00000000",
        //"editorIndentGuide.activeBackground5": "#00000000",
        //"editorIndentGuide.activeBackground6": "#00000000",
        //"editorIndentGuide.background1": "#6e6a8666",
        //"editorIndentGuide.background2": "#00000000",
        //"editorIndentGuide.background3": "#00000000",
        //"editorIndentGuide.background4": "#00000000",
        //"editorIndentGuide.background5": "#00000000",
        //"editorIndentGuide.background6": "#00000000",
        //"editorLightBulbAi.foreground": "#31748f",
        //"editorMarkerNavigationError.headerBackground": "#2222221a",
        //"editorMarkerNavigationInfo.headerBackground": "#2222221a",
        //"editorMarkerNavigationWarning.headerBackground": "#2222221a",
        //"editorMultiCursor.primary.background": "#000000",
        //"editorMultiCursor.primary.foreground": "#ffffff",
        //"editorMultiCursor.secondary.background": "#000000",
        //"editorMultiCursor.secondary.foreground": "#ffffff",
        //"editorOverviewRuler.inlineChatInserted": "#9ccfd817",
        //"editorOverviewRuler.inlineChatRemoved": "#eb6f9217",
        //"editorOverviewRuler.wordHighlightTextForeground": "#6e6a8666",
        //"editorStickyScroll.background": "#222222",
        //"editorStickyScroll.shadow": "#2222224d",
        //"editorStickyScrollHover.background": "#2a2d2e",
        //"editorSuggestWidgetStatus.foreground": "#908caa80",
        //"editorUnicodeHighlight.border": "#00000000",
        //"editorWatermark.foreground": "#e0def499",
        //"errorLens.errorBackground": "#e454541b",
        //"errorLens.errorBackgroundLight": "#e4545420",
        //"errorLens.errorForeground": "#ff6464",
        //"errorLens.errorForegroundLight": "#e45454",
        //"errorLens.errorMessageBackground": "#e4545419",
        //"errorLens.errorRangeBackground": "#e4545419",
        //"errorLens.hintBackground": "#17a2a220",
        //"errorLens.hintBackgroundLight": "#17a2a220",
        //"errorLens.hintForeground": "#2faf64",
        //"errorLens.hintForegroundLight": "#2faf64",
        //"errorLens.hintMessageBackground": "#17a2a219",
        //"errorLens.hintRangeBackground": "#17a2a219",
        //"errorLens.infoBackground": "#00b7e420",
        //"errorLens.infoBackgroundLight": "#00b7e420",
        //"errorLens.infoForeground": "#00b7e4",
        //"errorLens.infoForegroundLight": "#00b7e4",
        //"errorLens.infoMessageBackground": "#00b7e419",
        //"errorLens.infoRangeBackground": "#00b7e419",
        //"errorLens.statusBarErrorForeground": "#ff6464",
        //"errorLens.statusBarHintForeground": "#2faf64",
        //"errorLens.statusBarIconErrorForeground": "#ff6464",
        //"errorLens.statusBarIconWarningForeground": "#fa973a",
        //"errorLens.statusBarInfoForeground": "#00b7e4",
        //"errorLens.statusBarWarningForeground": "#fa973a",
        //"errorLens.warningBackground": "#ff942f1b",
        //"errorLens.warningBackgroundLight": "#ff942f20",
        //"errorLens.warningForeground": "#fa973a",
        //"errorLens.warningForegroundLight": "#ff942f",
        //"errorLens.warningMessageBackground": "#ff942f19",
        //"errorLens.warningRangeBackground": "#ff942f19",
        //"extensionButton.background": "#ebbcba",
        //"extensionButton.foreground": "#191724",
        //"extensionButton.hoverBackground": "#ebbcbae6",
        //"extensionButton.separator": "#19172466",
        //"extensionIcon.sponsorForeground": "#d758b3",
        //"inlineChat.background": "#222222",
        //"inlineChat.border": "#26233a",
        //"inlineChat.foreground": "#908caa",
        //"inlineChat.shadow": "#2222224d",
        //"inlineChatDiff.inserted": "#9ccfd813",
        //"inlineChatDiff.removed": "#eb6f9213",
        //"inlineChatInput.background": "#26233a80",
        //"inlineChatInput.border": "#26233a",
        //"inlineChatInput.focusBorder": "#6e6a8633",
        //"inlineChatInput.placeholderForeground": "#908caa",
        //"inlineEdit.border": "#00000000",
        //"inlineEdit.indicator.background": "#222222",
        //"inlineEdit.indicator.border": "#6e6a8680",
        //"inlineEdit.indicator.foreground": "#908caa",
        //"inlineEdit.modifiedBackground": "#9ccfd80f",
        //"inlineEdit.originalBackground": "#eb6f920f",
        //"inputOption.hoverBackground": "#5a5d5e80",
        //"interactive.activeCodeBorder": "#26233a",
        //"interactive.inactiveCodeBorder": "#222222",
        //"list.dropBetweenBackground": "#908caa",
        //"list.focusHighlightForeground": "#ebbcba",
        //"listFilterWidget.shadow": "#2222224d",
        //"mergeEditor.change.background": "#9bb95533",
        //"mergeEditor.change.word.background": "#9ccc2c33",
        //"mergeEditor.changeBase.background": "#4b1818",
        //"mergeEditor.changeBase.word.background": "#6f1313",
        //"mergeEditor.conflict.handled.minimapOverViewRuler": "#adaca8ee",
        //"mergeEditor.conflict.handledFocused.border": "#c1c1c1cc",
        //"mergeEditor.conflict.handledUnfocused.border": "#86868649",
        //"mergeEditor.conflict.input1.background": "#f6c17733",
        //"mergeEditor.conflict.input2.background": "#9ccfd833",
        //"mergeEditor.conflict.unhandled.minimapOverViewRuler": "#fcba03",
        //"mergeEditor.conflict.unhandledFocused.border": "#ffa600",
        //"mergeEditor.conflict.unhandledUnfocused.border": "#ffa6007a",
        //"mergeEditor.conflictingLines.background": "#ffea0047",
        //"minimap.foregroundOpacity": "#000000",
        //"minimap.infoHighlight": "#00000000",
        //"minimap.selectionOccurrenceHighlight": "#676767",
        //"multiDiffEditor.background": "#222222",
        //"multiDiffEditor.border": "#6e6a8633",
        //"multiDiffEditor.headerBackground": "#262626",
        //"notebook.cellInsertionIndicator": "#6e6a8633",
        //"notebook.cellStatusBarItemHoverBackground": "#ffffff26",
        //"notebook.cellToolbarSeparator": "#80808059",
        //"notebook.editorBackground": "#00000000",
        //"notebook.focusedEditorBorder": "#6e6a8633",
        //"notebook.inactiveFocusedCellBorder": "#9ccfd880",
        //"notebook.selectedCellBackground": "#222222",
        //"notebook.selectedCellBorder": "#9ccfd880",
        //"notebook.symbolHighlightBackground": "#ffffff0b",
        //"notebookEditorOverviewRuler.runningCellForeground": "#908caa",
        //"notebookScrollbarSlider.activeBackground": "#222222",
        //"notebookScrollbarSlider.background": "#222222",
        //"notebookScrollbarSlider.hoverBackground": "#222222",
        //"notebookStatusErrorIcon.foreground": "#eb6f92",
        //"notebookStatusRunningIcon.foreground": "#e0def4",
        //"notebookStatusSuccessIcon.foreground": "#908caa",
        //"panelSection.border": "#00000000",
        //"panelStickyScroll.background": "#222222",
        //"panelStickyScroll.shadow": "#2222224d",
        //"peekViewEditorGutter.background": "#2e2e2e",
        //"peekViewEditorStickyScroll.background": "#2e2e2e",
        //"peekViewTitleLabel.foreground": "#ffffff",
        //"profileBadge.background": "#4d4d4d",
        //"profileBadge.foreground": "#ffffff",
        //"profiles.sashBorder": "#00000000",
        //"quickInputTitle.background": "#ffffff1b",
        //"radio.activeBackground": "#ebbcba26",
        //"radio.activeBorder": "#00000000",
        //"radio.activeForeground": "#ebbcba",
        //"radio.inactiveBorder": "#ebbcba33",
        //"radio.inactiveHoverBackground": "#5a5d5e80",
        //"rust_analyzer.syntaxTreeBorder": "#ffffff",
        //"sash.hoverBorder": "#6e6a8633",
        //"scmGraph.foreground1": "#ffb000",
        //"scmGraph.foreground2": "#dc267f",
        //"scmGraph.foreground3": "#994f00",
        //"scmGraph.foreground4": "#40b0a6",
        //"scmGraph.foreground5": "#b66dff",
        //"scmGraph.historyItemBaseRefColor": "#ea5c00",
        //"scmGraph.historyItemHoverAdditionsForeground": "#81b88b",
        //"scmGraph.historyItemHoverDefaultLabelBackground": "#ebbcba",
        //"scmGraph.historyItemHoverDefaultLabelForeground": "#e0def4",
        //"scmGraph.historyItemHoverDeletionsForeground": "#c74e39",
        //"scmGraph.historyItemHoverLabelForeground": "#191724",
        //"scmGraph.historyItemRefColor": "#9ccfd8",
        //"scmGraph.historyItemRemoteRefColor": "#c4a7e7",
        //"search.resultsInfoForeground": "#e0def4a6",
        //"searchEditor.textInputBorder": "#6e6a8633",
        //"settings.checkboxBackground": "#222222",
        //"settings.checkboxBorder": "#6e6a8633",
        //"settings.checkboxForeground": "#e0def4",
        //"settings.dropdownBackground": "#222222",
        //"settings.dropdownBorder": "#6e6a8633",
        //"settings.dropdownForeground": "#e0def4",
        //"settings.dropdownListBorder": "#26233a",
        //"settings.headerBorder": "#00000000",
        //"settings.numberInputBackground": "#26233a80",
        //"settings.numberInputBorder": "#6e6a8633",
        //"settings.numberInputForeground": "#e0def4",
        //"settings.sashBorder": "#00000000",
        //"settings.settingsHeaderHoverForeground": "#e0def4b3",
        //"settings.textInputBackground": "#26233a80",
        //"settings.textInputBorder": "#6e6a8633",
        //"settings.textInputForeground": "#e0def4",
        //"sideBarActivityBarTop.border": "#6e6a8633",
        //"sideBarStickyScroll.background": "#222222",
        //"sideBarStickyScroll.shadow": "#2222224d",
        //"sideBarTitle.background": "#222222",
        //"sideBarTitle.foreground": "#a7a7a7",
        //"sideBySideEditor.horizontalBorder": "#00000000",
        //"sideBySideEditor.verticalBorder": "#00000000",
        //"simpleFindWidget.sashBorder": "#454545",
        //"statusBar.focusBorder": "#a7a7a7",
        //"statusBarItem.compactHoverBackground": "#ffffff33",
        //"statusBarItem.errorHoverBackground": "#6e6a8633",
        //"statusBarItem.errorHoverForeground": "#a7a7a7",
        //"statusBarItem.focusBorder": "#a7a7a7",
        //"statusBarItem.hoverForeground": "#a7a7a7",
        //"statusBarItem.offlineBackground": "#6c1717",
        //"statusBarItem.offlineForeground": "#f6c177",
        //"statusBarItem.offlineHoverBackground": "#6e6a8633",
        //"statusBarItem.offlineHoverForeground": "#a7a7a7",
        //"statusBarItem.prominentHoverForeground": "#a7a7a7",
        //"statusBarItem.remoteHoverBackground": "#6e6a8633",
        //"statusBarItem.remoteHoverForeground": "#a7a7a7",
        //"statusBarItem.warningBackground": "#00000000",
        //"statusBarItem.warningForeground": "#ffffff",
        //"statusBarItem.warningHoverBackground": "#6e6a8633",
        //"statusBarItem.warningHoverForeground": "#a7a7a7",
        //"symbolIcon.booleanForeground": "#e0def4",
        //"tab.dragAndDropBorder": "#e0def4",
        //"tab.selectedBackground": "#6e6a861a",
        //"tab.selectedForeground": "#e0def4",
        //"tab.unfocusedActiveForeground": "#e0def480",
        //"tab.unfocusedActiveModifiedBorder": "#9ccfd880",
        //"tab.unfocusedInactiveForeground": "#908caa80",
        //"terminal.border": "#00000000",
        //"terminal.findMatchBackground": "#f6c17733",
        //"terminal.findMatchHighlightBackground": "#6e6a8666",
        //"terminal.hoverHighlightBackground": "#00000000",
        //"terminal.inactiveSelectionBackground": "#6e6a861a",
        //"terminal.initialHintForeground": "#ffffff56",
        //"terminalCommandDecoration.defaultBackground": "#ffffff40",
        //"terminalCommandDecoration.errorBackground": "#f14c4c",
        //"terminalCommandDecoration.successBackground": "#1b81a8",
        //"terminalCommandGuide.foreground": "#222222",
        //"terminalOverviewRuler.border": "#6e6a8666",
        //"terminalOverviewRuler.cursorForeground": "#a0a0a0cc",
        //"terminalOverviewRuler.findMatchForeground": "#6e6a8666",
        //"terminalStickyScrollHover.background": "#2a2d2e",
        //"testing.coverCountBadgeBackground": "#ebbcba",
        //"testing.coverCountBadgeForeground": "#191724",
        //"testing.coveredBackground": "#9ccfd826",
        //"testing.coveredBorder": "#9ccfd81d",
        //"testing.coveredGutterBackground": "#9ccfd817",
        //"testing.iconErrored": "#f14c4c",
        //"testing.iconErrored.retired": "#f14c4cb3",
        //"testing.iconFailed": "#f14c4c",
        //"testing.iconFailed.retired": "#f14c4cb3",
        //"testing.iconPassed": "#73c991",
        //"testing.iconPassed.retired": "#73c991b3",
        //"testing.iconQueued": "#cca700",
        //"testing.iconQueued.retired": "#cca700b3",
        //"testing.iconSkipped": "#848484",
        //"testing.iconSkipped.retired": "#848484b3",
        //"testing.iconUnset": "#848484",
        //"testing.iconUnset.retired": "#848484b3",
        //"testing.message.error.decorationForeground": "#00000000",
        //"testing.message.error.lineBackground": "#ff00001a",
        //"testing.message.info.decorationForeground": "#e0def480",
        //"testing.messagePeekBorder": "#00000000",
        //"testing.messagePeekHeaderBackground": "#00000000",
        //"testing.peekBorder": "#00000000",
        //"testing.peekHeaderBackground": "#00000000",
        //"testing.runAction": "#73c991",
        //"testing.uncoveredBackground": "#eb6f9226",
        //"testing.uncoveredBorder": "#eb6f921d",
        //"testing.uncoveredBranchBackground": "#5d3843",
        //"testing.uncoveredGutterBackground": "#eb6f9239",
        //"textPreformat.background": "#ffffff1a",
        //"tree.inactiveIndentGuidesStroke": "#908caa66",
        //"tree.tableColumnsBorder": "#cccccc20",
        //"tree.tableOddRowsBackground": "#e0def40a",
        //"walkthrough.stepTitle.foreground": "#ffffff",
        //"welcomePage.progress.background": "#26233a80",
        //"welcomePage.progress.foreground": "#c4a7e7",
        //"welcomePage.tileBackground": "#222222",
        //"welcomePage.tileBorder": "#ffffff1a",
        //"welcomePage.tileHoverBackground": "#252337",
        //"activityBar.activeBackground": null,
        //"activityBar.activeFocusBorder": null,
        //"activityBar.border": null,
        //"activityBarTop.activeBackground": null,
        //"activityBarTop.background": null,
        //"button.border": null,
        //"contrastActiveBorder": null,
        //"contrastBorder": null,
        //"diffEditor.insertedTextBorder": null,
        //"diffEditor.removedTextBorder": null,
        //"diffEditorGutter.insertedLineBackground": null,
        //"diffEditorGutter.removedLineBackground": null,
        //"editor.findMatchHighlightBorder": null,
        //"editor.rangeHighlightBorder": null,
        //"editorError.background": null,
        //"editorGhostText.background": null,
        //"editorGhostText.border": null,
        //"editorGroup.dropIntoPromptBorder": null,
        //"editorGroupHeader.border": null,
        //"editorInfo.background": null,
        //"editorLineNumber.dimmedForeground": null,
        //"editorStickyScroll.border": null,
        //"editorUnicodeHighlight.background": null,
        //"editorWarning.background": null,
        //"list.activeSelectionIconForeground": null,
        //"list.focusAndSelectionOutline": null,
        //"list.inactiveFocusOutline": null,
        //"list.inactiveSelectionIconForeground": null,
        //"notebook.inactiveSelectedCellBorder": null,
        //"notebook.outputContainerBorderColor": null,
        //"outputView.background": null,
        //"outputViewStickyScroll.background": null,
        //"panelSectionHeader.border": null,
        //"panelStickyScroll.border": null,
        //"peekViewEditor.matchHighlightBorder": null,
        //"quickInput.list.focusBackground": null,
        //"radio.inactiveBackground": null,
        //"radio.inactiveForeground": null,
        //"searchEditor.findMatchBorder": null,
        //"sideBar.border": null,
        //"sideBarStickyScroll.border": null,
        //"statusBar.border": null,
        //"statusBar.debuggingBorder": null,
        //"statusBar.noFolderBorder": null,
        //"tab.activeBorder": null,
        //"tab.activeBorderTop": null,
        //"tab.hoverBorder": null,
        //"tab.hoverForeground": null,
        //"tab.selectedBorderTop": null,
        //"tab.unfocusedActiveBorder": null,
        //"tab.unfocusedActiveBorderTop": null,
        //"tab.unfocusedHoverBorder": null,
        //"tab.unfocusedHoverForeground": null,
        //"terminal.background": null,
        //"terminal.findMatchBorder": null,
        //"terminal.findMatchHighlightBorder": null,
        //"terminal.selectionForeground": null,
        //"terminalStickyScroll.background": null,
        //"terminalStickyScroll.border": null,
        //"testing.message.info.lineBackground": null,
        //"titleBar.border": null,
        //"toolbar.hoverOutline": null,
        //"widget.border": null
    },
    "tokenColors": [
        {
            "scope": [
                "comment"
            ],
            "settings": {
                "foreground": "#6E6A86",
                "fontStyle": ""
            }
        },
        {
            "scope": [
                "constant"
            ],
            "settings": {
                "foreground": "#31748F"
            }
        },
        {
            "scope": [
                "constant.numeric",
                "constant.language"
            ],
            "settings": {
                "foreground": "#EBBCBA"
            }
        },
        {
            "scope": [
                "entity.name"
            ],
            "settings": {
                "foreground": "#EBBCBA"
            }
        },
        {
            "scope": [
                "entity.name.section",
                "entity.name.tag",
                "entity.name.namespace",
                "entity.name.type"
            ],
            "settings": {
                "foreground": "#9CCFD8"
            }
        },
        {
            "scope": [
                "entity.other.attribute-name",
                "entity.other.inherited-class"
            ],
            "settings": {
                "foreground": "#C4A7E7",
                "fontStyle": ""
            }
        },
        {
            "scope": [
                "invalid"
            ],
            "settings": {
                "foreground": "#EB6F92"
            }
        },
        {
            "scope": [
                "invalid.deprecated"
            ],
            "settings": {
                "foreground": "#908CAA"
            }
        },
        {
            "scope": [
                "keyword",
                "variable.language.this"
            ],
            "settings": {
                "foreground": "#31748F"
            }
        },
        {
            "scope": [
                "markup.inserted.diff"
            ],
            "settings": {
                "foreground": "#9CCFD8"
            }
        },
        {
            "scope": [
                "markup.deleted.diff"
            ],
            "settings": {
                "foreground": "#EB6F92"
            }
        },
        {
            "scope": "markup.heading",
            "settings": {
                "fontStyle": "bold"
            }
        },
        {
            "scope": "markup.bold.markdown",
            "settings": {
                "fontStyle": "bold"
            }
        },
        {
            "scope": "markup.italic.markdown",
            "settings": {
                "fontStyle": ""
            }
        },
        {
            "scope": [
                "meta.diff.range"
            ],
            "settings": {
                "foreground": "#C4A7E7"
            }
        },
        {
            "scope": [
                "meta.tag",
                "meta.brace"
            ],
            "settings": {
                "foreground": "#E0DEF4"
            }
        },
        {
            "scope": [
                "meta.import",
                "meta.export"
            ],
            "settings": {
                "foreground": "#31748F"
            }
        },
        {
            "scope": "meta.directive.vue",
            "settings": {
                "foreground": "#C4A7E7",
                "fontStyle": ""
            }
        },
        {
            "scope": "meta.property-name.css",
            "settings": {
                "foreground": "#9CCFD8"
            }
        },
        {
            "scope": "meta.property-value.css",
            "settings": {
                "foreground": "#F6C177"
            }
        },
        {
            "scope": "meta.tag.other.html",
            "settings": {
                "foreground": "#908CAA"
            }
        },
        {
            "scope": [
                "punctuation"
            ],
            "settings": {
                "foreground": "#908CAA"
            }
        },
        {
            "scope": [
                "punctuation.accessor"
            ],
            "settings": {
                "foreground": "#31748F"
            }
        },
        {
            "scope": [
                "punctuation.definition.string"
            ],
            "settings": {
                "foreground": "#F6C177"
            }
        },
        {
            "scope": [
                "punctuation.definition.tag"
            ],
            "settings": {
                "foreground": "#6E6A86"
            }
        },
        {
            "scope": [
                "storage.type",
                "storage.modifier"
            ],
            "settings": {
                "foreground": "#31748F"
            }
        },
        {
            "scope": [
                "string"
            ],
            "settings": {
                "foreground": "#F6C177"
            }
        },
        {
            "scope": [
                "support"
            ],
            "settings": {
                "foreground": "#9CCFD8"
            }
        },
        {
            "scope": [
                "support.constant"
            ],
            "settings": {
                "foreground": "#F6C177"
            }
        },
        {
            "scope": [
                "support.function"
            ],
            "settings": {
                "foreground": "#EB6F92",
                "fontStyle": ""
            }
        },
        {
            "scope": [
                "variable"
            ],
            "settings": {
                "foreground": "#EBBCBA",
                "fontStyle": ""
            }
        },
        {
            "scope": [
                "variable.other",
                "variable.language",
                "variable.function",
                "variable.argument"
            ],
            "settings": {
                "foreground": "#E0DEF4"
            }
        },
        {
            "scope": [
                "variable.parameter"
            ],
            "settings": {
                "foreground": "#C4A7E7"
            }
        },
        {
            "scope": "token.info-token",
            "settings": {
                "foreground": "#6796E6"
            }
        },
        {
            "scope": "token.warn-token",
            "settings": {
                "foreground": "#CD9731"
            }
        },
        {
            "scope": "token.error-token",
            "settings": {
                "foreground": "#F44747"
            }
        },
        {
            "scope": "token.debug-token",
            "settings": {
                "foreground": "#B267E6"
            }
        }
    ]
}